# Use postgres/example user/password credentials
version: '3.1'

volumes:
  data:


services:
  postgres:
    container_name: postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: butterfly
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data
